services:
  app:
    build:
      args:
        user: dani
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ereport-erenos
    container_name: ereport-erenos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ereport-erenos

  nginx:
    image: nginx:alpine
    container_name: ereport-erenos-nginx
    restart: unless-stopped
    ports:
      - 8125:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - ereport-erenos

  db:
    image: mysql:8.0
    container_name: ereport-erenos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3308:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ereport-erenos
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ereport-erenos-phpmyadmin
    links:
      - db
    restart: unless-stopped
    ports:
      - 8126:80
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    networks:
      - ereport-erenos

networks:
  ereport-erenos:
    driver: bridge